In [1]:
import pandas as pd
import numpy as np

In [43]:
pd.isnull(test).any(axis=1).to_numpy().nonzero()

(array([8416, 9432], dtype=int64),)

In [68]:
test.isna().any(1).to_numpy().nonzero()

(array([8416, 9432], dtype=int64),)

In [35]:
df = pd.read_csv('BMRS_2021/Imbalance_Volume_2021.csv')
df

local_datetime  settlementPeriod  imbalanceQuantityMAW
0     2021-01-01 00:00:00+00:00                 1              843.6931
1     2021-01-01 00:30:00+00:00                 2              934.5820
2     2021-01-01 01:00:00+00:00                 3              604.7328
3     2021-01-01 01:30:00+00:00                 4              307.3387
4     2021-01-01 02:00:00+00:00                 5               48.8845
...                         ...               ...                   ...
5753  2021-04-30 21:30:00+01:00                44              224.0560
5754  2021-04-30 22:00:00+01:00                45              315.6673
5755  2021-04-30 22:30:00+01:00                46              165.2474
5756  2021-04-30 23:00:00+01:00                47              261.7062
5757  2021-04-30 23:30:00+01:00                48              395.0930

[5758 rows x 3 columns]

In [31]:
df.duplicated(subset=['local_datetime','settlementPeriod']).to_numpy().nonzero()

(array([], dtype=int64),)

In [36]:
df1 = df.drop_duplicates(subset=['local_datetime', 'settlementPeriod'],keep='first')
df2 = df1[['local_datetime','quantity']]
df2

local_datetime  imbalanceQuantityMAW
0     2021-01-01 00:00:00+00:00              843.6931
1     2021-01-01 00:30:00+00:00              934.5820
2     2021-01-01 01:00:00+00:00              604.7328
3     2021-01-01 01:30:00+00:00              307.3387
4     2021-01-01 02:00:00+00:00               48.8845
...                         ...                   ...
5753  2021-04-30 21:30:00+01:00              224.0560
5754  2021-04-30 22:00:00+01:00              315.6673
5755  2021-04-30 22:30:00+01:00              165.2474
5756  2021-04-30 23:00:00+01:00              261.7062
5757  2021-04-30 23:30:00+01:00              395.0930

[5758 rows x 2 columns]

In [8]:
gd = pd.read_csv('BMRS_2021/Actual_Solar_Generation_2021.csv')

In [9]:
gd.drop_duplicates(subset=['local_datetime', 'settlementPeriod'])

local_datetime  settlementPeriod  quantity
0     2021-01-01 00:00:00+00:00                 1         0
1     2021-01-01 00:30:00+00:00                 2         1
2     2021-01-01 01:00:00+00:00                 3         1
3     2021-01-01 01:30:00+00:00                 4         0
4     2021-01-01 02:00:00+00:00                 5         0
...                         ...               ...       ...
5753  2021-04-30 21:30:00+01:00                44         2
5754  2021-04-30 22:00:00+01:00                45         1
5755  2021-04-30 22:30:00+01:00                46         0
5756  2021-04-30 23:00:00+01:00                47         1
5757  2021-04-30 23:30:00+01:00                48         1

[5758 rows x 3 columns]

In [25]:
df3 = pd.merge(gd,df2,on='local_datetime',how='left')
df3

local_datetime  settlementPeriod  quantity_x  quantity_y
0     2021-01-01 00:00:00+00:00                 1           0       30006
1     2021-01-01 00:30:00+00:00                 2           1       29911
2     2021-01-01 01:00:00+00:00                 3           1       29209
3     2021-01-01 01:30:00+00:00                 4           0       28041
4     2021-01-01 02:00:00+00:00                 5           0       27243
...                         ...               ...         ...         ...
5753  2021-04-30 21:30:00+01:00                44           2       31810
5754  2021-04-30 22:00:00+01:00                45           1       30150
5755  2021-04-30 22:30:00+01:00                46           0       28291
5756  2021-04-30 23:00:00+01:00                47           1       26626
5757  2021-04-30 23:30:00+01:00                48           1       25379

[5758 rows x 4 columns]

In [26]:
df3.isna().any()

local_datetime      False
settlementPeriod    False
quantity_x          False
quantity_y          False
dtype: bool

In [12]:
df3.isna().any(1).to_numpy().nonzero()

(array([1062, 1474, 5152], dtype=int64),)

In [82]:
# fill na with mean of the column
# df3['quantity'].fillna(round(df3['quantity'].mean()), inplace=True)

In [14]:
# fill na with mean of adjacent elements
df3['quantity_y'] = round((df3['quantity_y'].ffill()+df3['quantity_y'].bfill())/2, 0)

In [15]:
df3.isna().any()

local_datetime      False
settlementPeriod    False
quantity_x          False
quantity_y          False
dtype: bool

In [27]:
df4 = df3[['local_datetime','settlementPeriod','quantity_y']]
df4

local_datetime  settlementPeriod  quantity_y
0     2021-01-01 00:00:00+00:00                 1       30006
1     2021-01-01 00:30:00+00:00                 2       29911
2     2021-01-01 01:00:00+00:00                 3       29209
3     2021-01-01 01:30:00+00:00                 4       28041
4     2021-01-01 02:00:00+00:00                 5       27243
...                         ...               ...         ...
5753  2021-04-30 21:30:00+01:00                44       31810
5754  2021-04-30 22:00:00+01:00                45       30150
5755  2021-04-30 22:30:00+01:00                46       28291
5756  2021-04-30 23:00:00+01:00                47       26626
5757  2021-04-30 23:30:00+01:00                48       25379

[5758 rows x 3 columns]

In [28]:
df4.to_csv('DA_Load_Forecast_2021.csv',index=False)